spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  cache:
    type:  caffeine
    caffeine:
      spec: maximumSize=500,expireAfterAccess=600s
 
logging:
  level:
    com.nt : DEBUG
    com.razorpay: INFO

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect


server:
  port: ${PORT:8080}
#  ssl:
#   enabled: true
#   key-store: classpath:keystore.p12
#   key-store-password: ${KEYSTORE_PASSWORD:Sandeep@123}
#   key-store-type: PKCS12
#   key-alias: tomcat

app:
   cors:
      allowed-origins:
         - http://localhost:5173
         - http://localhost:3000
         - http://127.0.0.1:3000
         - https://first-kitchen-frontend-new.vercel.app

razorpay:
   key:
      id: ${RAZORPAY_ID}
      secret : ${RAZORPAY_SECRETE}
   webhook:
      secret: ${WEB_HOOK_SECRETE}
retry:
   max-attempts: 3
   backoff-delay: 1000



