spring:
  profiles:
    active: dev
  application:
    name: FirstKitchen
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql:///firstkitchen
    username: root
    password: dummany@123
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
server:
  port: 9009
  servlet:
    context-path: /FirstKitchen

jwt:
   secret: 5367566859703373367639792F423F452848284D6251655468576D5A71347437
