spring:
  profiles:
    active: prod
  application:
    name: FirstKitchen
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql:///firstkitchen
    username: root
    password: Sandeep@123
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
server:
  port: 9009
  ssl:
     enabled: true
     key-store: classpath:keystore.p12
     key-store-password: Sandeep@123
     key-store-type: PKCS12
     key-alias: tomcat
  servlet:
    context-path: /FirstKitchen

jwt:
   secret: 5367566859703373367639792F423F452848284D6251655468576D5A71347437
